apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: assessment
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: example
  MONGODB_URI: mongodb://root:example@mongo:27017/mern-auth?authSource=admin
  JWT_SECRET: assessment-demo-secret
